export const THEMES = [
  { id: "light", label: "Light" },
  { id: "dark", label: "Dark" },
  { id: "cupcake", label: "Cupcake" },
  { id: "bumblebee", label: "Bumblebee" },
  { id: "emerald", label: "Emerald" },
  { id: "corporate", label: "Corporate" },
  { id: "synthwave", label: "Synthwave" },
  { id: "retro", label: "Retro" },
  { id: "cyberpunk", label: "Cyberpunk" },
  { id: "valentine", label: "Valentine" },
  { id: "halloween", label: "Halloween" },
  { id: "garden", label: "Garden" },
  { id: "forest", label: "Forest" },
  { id: "aqua", label: "Aqua" },
  { id: "lofi", label: "Lofi" },
  { id: "pastel", label: "Pastel" },
  { id: "fantasy", label: "Fantasy" },
  { id: "wireframe", label: "Wireframe" },
  { id: "black", label: "Black" },
  { id: "luxury", label: "Luxury" },
  { id: "dracula", label: "Dracula" },
  { id: "cmyk", label: "CMYK" },
  { id: "autumn", label: "Autumn" },
  { id: "business", label: "Business" },
  { id: "acid", label: "Acid" },
  { id: "lemonade", label: "Lemonade" },
  { id: "night", label: "Night" },
  { id: "coffee", label: "Coffee" },
  { id: "winter", label: "Winter" },
  { id: "dim", label: "Dim" },
  { id: "nord", label: "Nord" },
  { id: "sunset", label: "Sunset" },
];

